name: Feature Branch

on:
  push:
    branches:
      - '*'
jobs:
  test:

    runs-on: ubuntu-latest

    env:
      CI: true

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
#          cache: 'pnpm' TODO
#          cache-dependency-path: ./pnpm-lock.yaml
      - run: pnpm ci
        name: Install
      - run: npm run test
        name: Test
