name: Feature Branch

on:
  push:
    branches:
      - '*'
jobs:
  test:

    runs-on: ubuntu-latest

    env:
      CI: true

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
#          cache: 'pnpm' TODO
#          cache-dependency-path: ./pnpm-lock.yaml
      - run: pnpm ci
        name: Install
      - run: npm run test
        name: Test
